### PR TITLE
Feature/ai tree

### PR DESCRIPTION
**Pull request by Toine2106**

### CODE REVIEW

**Comment by TimothyTichelaar** [comment]
You can run through the enemy when walking against him and attacking

**Review by TimothyTichelaar — DISMISSED** [review]
Oke, omdat Wouter het al had gefixt

**Review by TimothyTichelaar — APPROVED** [review]
pls review my search behaviour, I'm not going to review my own work. I allready approved your work last time, for no its good

**Review by Toine2106 — COMMENTED** [review]
Files look oke and good implemented. 
testing in unity failed no search behavior and no debug logs in unity

**Comment by Justwouter** [comment]
Search looks good, can you add a navmesh etc to the village level @Toine2106? The AI currently crashes the game when loading it.

**Comment by Justwouter** [comment]
Why is that whole get, set and clear data system included if data is never set or get and cleared twice?

**Pull request merged**
