### PR TITLE
feature: fx.particles.bush ^ 2

### PR DESCRIPTION
**Pull request by hexaclue**
Adds particles to bush interactions!

**How to use:**
Add the `InteractablePopulator` to the tileset GameObject, then assign the `PrefabInteractable` field a prefab. On start, the populator will instantiate the prefab at the center of every position of every filled tile in the tileset.

TODO for @Justwouter:
- [x] "Fix dat hij ipv op "interaction", oftewel een E press, actieert bij een attack pls" - @TimothyTichelaar 

This PR replaces PR #71 because of the new map system.

### CODE REVIEW

**Comment by Justwouter** [comment]
Fun fact, I can't even open the project without getting at least 6 compiler errors, every single interaction point has apparently had its components removed and the Wwise api which we seem to use now blowing up the console.

Not looking at this until it is at least functional.

**Comment by hexaclue** [comment]
Linux issue

**Comment by TimothyTichelaar** [comment]
Wwise: Voice Starvation
UnityEngine.Debug:LogError (object)
AkCallbackManager:PostCallbacks () (at Assets/Wwise/API/Runtime/Handwritten/Common/AkCallbackManager.cs:392)
AkSoundEngineController:LateUpdate () (at Assets/Wwise/MonoBehaviour/Runtime/AkSoundEngineController.cs:84)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()


Got this error upon playing, Bush interactions dont work because of this

**Comment by hexaclue** [comment]
Works for me, try stopping Unity, switching to dev, switching back to this branch, then reopening Unity and scene `4-Overworld`. It however does not contain the populator yet, but can easily be added to the bush tileset layer

https://github.com/smooth-soup-studios/oh-my-cult/assets/26181740/35914186-60aa-40fe-bf1f-2970efcf05ec

**Comment by hexaclue** [comment]
Just to be sure: on which platform are you building? Wwise seems to not support WebGL builds @Justwouter @TimothyTichelaar

**Comment by SyncMQ** [comment]
> Wwise: Voice Starvation 
> UnityEngine.Debug:LogError (object) AkCallbackManager:PostCallbacks () (at Assets/Wwise/API/Runtime/Handwritten/Common/AkCallbackManager.cs:392) AkSoundEngineController:LateUpdate () (at Assets/Wwise/MonoBehaviour/Runtime/AkSoundEngineController.cs:84) UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
> 
> Got this error upon playing, Bush interactions dont work because of this


The voice starvation can be safely ignored since it appears whenever the CPU load is too high/almost maxed which causes the audio engine to not produce sound as well. Should rarely happen in editor and never in builds.
~~Did you do something in-game that this showed up or did it just show up on pull?~~
[EDIT: never mind, saw that this was also part of voice starvation error. You can run the game regardless of the error.]

**Comment by Justwouter** [comment]
Already merged via #86

**Pull request closed without merging**
