### PR TITLE
feature: fx.particles.bush

### PR DESCRIPTION
**Pull request by hexaclue**
Add bush particles on interact with `BushInteractable`. Could/should be on attack, but that isn't implemented in `BaseInteractable`.

Also implements `InteractablePopulator`, which could be of use when adding other multi-instance interactables such as barrels, trees and more.

A test scene is provided (`/Assets/Scenes/testing/BushInteractorTest/bush_interactor.unity`)

### CODE REVIEW

**Review by TimothyTichelaar — COMMENTED** [review]
@Justwouter Fix dat hij ipv op "interaction", oftewel een E press, actieert bij een attack pls

**Comment by Justwouter** [comment]
Why did you make the populator when entities in LdTk can also be used?

**Comment by hexaclue** [comment]
These are, in fact, LDtk entities. This is however just the branch for the playtest tomorrow so it'll suffice I think.

To use, pair up the names of the entities and layer(s) in the script fields with the ones in LDtk

**Comment by Justwouter** [comment]
I know that they are linked to LdTk entities etc but inside the level asset you can already assign an prefab to each entity which will be placed in the scene exactly like the populator appears to do.

So my question is: are you aware of this and if so, why is this populator script better?

**Comment by hexaclue** [comment]
I was half aware of it, but did not look further into it. Using the populator will be preferable/easier in the case of the new level system (Unity native tilemaps) instead of LDtk.

**Review by Justwouter — APPROVED** [review]
While I do agree that it is indeed useful in a native tilemap env, that is not relevant here as the map is still LtDk.
I do not agree with the inclusion of the populator -at least in its current state-. 
However the bush particles and the interactor itself are perfectly fine and can be included in dev in time for the playtest.

**Pull request merged**
